        NAME AVERAGE
        EXTRN TAB : BYTE
        PUBLIC AVERAGE
.386

SHOW MACRO S
  LEA DX, S
  MOV AH, 9
  INT 21H
  ENDM

DATA SEGMENT USE16 PARA PUBLIC 'DATA'
  DONE DB 'AVERAGE CACULATION DONE!', 0DH, 0AH, '$'
DATA ENDS

CODE SEGMENT USE16 PARA PUBLIC 'CODE'
  ASSUME CS : CODE, DS : DATA
AVERAGE PROC
  PUSH SI
  PUSH CX
  PUSH BX
  PUSH AX
  PUSH DX
  LEA SI,TAB
  MOV CX,5
AVE :
  MOVZX BX,BYTE PTR 10[SI]
  SHL BX,1
  MOVZX AX,BYTE PTR 11[SI]
  ADD BX,AX
  MOVZX AX,BYTE PTR 12[SI]
  SHR AX,1
  ADD AX,BX
  SHL AX,1
  MOV DL,7
  DIV DL
  MOV 13[SI],AL
  ADD SI,16
  LOOP AVE
  SHOW DONE
  POP DX
  POP AX
  POP BX
  POP CX
  POP SI
  RET
AVERAGE ENDP
CODE ENDS
  END
