;SUBFUNC CHECK_NAME OF MODULE INSERT
;TO CHECK THE NAME INPUTED LEGAL OR NOT
      NAME CHECK_NAME
      EXTRN BUF : BYTE, CRLF : BYTE, WRONG_NAME : BYTE
      PUBLIC CHECK_NAME
.386
CODE SEGMENT USE16 PARA PUBLIC 'CODE'
ASSUME CS:CODE

SHOW MACRO S
  LEA DX, S
  MOV AH, 9
  INT 21H
  ENDM
CHECK_NAME PROC
  PUSH CX
  PUSH SI
  PUSH DX
  MOV CX,10
  MOV SI,0
COPY :
  MOV DL,BUF[SI]+2
  CMP DL,0DH
  JZ BREAK1
  CMP DL,41H
  JB BAD
  CMP DL,5AH
  JNA CONTINUE
  CMP DL,61H
  JB BAD
  CMP DL,7AH
  JNA CONTINUE
BAD :
  SHOW WRONG_NAME
  SHOW CRLF
  MOV AX, 0
  JMP BREAK1
CONTINUE :
  CMP DL,61H
  JB LOWER
  SUB DL,20H
LOWER :
  MOV [BX+SI],DL
  INC SI
  LOOP COPY
BREAK1 :
  POP DX
  POP SI
  POP CX
  RET
CHECK_NAME ENDP
CODE ENDS
  END
