      NAME PRINT
      EXTRN RANK :NEAR, TAB : BYTE
      PUBLIC PRINT
.386

DATA SEGMENT USE16 PARA PUBLIC 'DATA'
FAC DB 10
BUF_SHOW DB 80 DUP(0)
DATA ENDS

CODE SEGMENT USE16 PARA PUBLIC 'CODE'
ASSUME CS:CODE,DS:DATA



PRINT PROC
PUSH AX
PUSH DX
PUSH CX
PUSH DI
PUSH SI
PUSH BX
PUSH BP
CALL RANK
MOV CX,0
MOV BX,0
MOV BP,0
LOPOT: MOV SI,0
       MOV DI,0
       ADD BX,16
       ADD BP,16
       INC CX
       CMP CX,6
       JE FLAG4
LOPIN :MOV AL,TAB[BX-16][SI]
       CMP AL,0
       JE FLAG3
       MOV DS:BUF_SHOW[BP-16][DI],AL
FLAG3: INC SI
       INC DI
       CMP SI,10
       JNE FLAG2
FLAG1: MOV SI,13
FLAG2: CMP SI,16
       JNE LOPIN
       MOV DS:BUF_SHOW[BP-16][15],'$'
       JMP LOPOT

FLAG4: MOV CX,0
       LEA SI,BUF_SHOW
CHG:   INC CX
       CMP CX,6
       JE NEXT
       XCHG [SI+11],AL
       MOV  [SI+14],AL
       MOV  AL,BYTE PTR [SI+10]
       MOV  AH,0
       DIV FAC
       ADD AL,48
       ADD AH,48

       MOV [SI+11],AL
       MOV [SI+12],AH
       ADD BYTE PTR [SI+14],48
       CMP BYTE PTR [SI+10],100
       JNE FLAG5
       MOV  BYTE PTR [SI+11],49
       MOV  BYTE PTR [SI+12],48
       MOV  BYTE PTR [SI+13],48
FLAG5: MOV  BYTE PTR [SI+10],0
       ADD SI,16
       JMP CHG


NEXT:MOV CX,0
     LEA SI,BUF_SHOW

LOP: INC CX
     MOV DX,SI
     MOV AH,9
     INT 21H
     ADD SI,16

     MOV DL,0AH
     MOV AH,2
     INT 21H

     CMP CX,5
     JNE LOP
POP BP
POP BX
POP SI
POP DI
POP CX
POP DX
POP AX
RET
PRINT ENDP
CODE ENDS
     END
